name: FILIAPOLIS FR
favicon: null
layout_spectrum: 0.41771433665417135
typography_spectrum: 0.5401842542923987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50765416-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.495268473867327
  lightness: 0.5875543139409274
  saturation: 0.4765617814846337
  rhythmicContrast: 0.30840640189126134
purpose: []
