name: FILIAPOLIS FR
favicon: null
layout_spectrum: 0.41771433665417135
typography_spectrum: 0.5401842542923987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50765416-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ba77'
    - '#e68231'
    - '#fbe4c2'
    - '#eca25c'
    - '#f7cf9c'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
